title: 'New Theme'
body:
 - type: markdown
   attributes:
     value: |
       Request adding a new theme to the public collection
       ## Checklist
       - Only submit your theme if you think others would need it. Quality over quantity
       - Check if the json is valid and works when you import it from `efy` > `backup`
       - Reduce the size or resolution of your images as much as possible (ideally between 50kb - 2mb) by compressing them and using formats like `webp` and `avif`
       - Remove unnecessary lines or content if other users won't need them
       - If you need help, let us know on matrix or here
 - type: input
   id: name
   attributes:
     label: "Name (required)"
   validations:
     required: true
 - type: input
   id: description
   attributes:
     label: "Description (optional)"
 - type: textarea
   id: json
   attributes:
     label: "JSON (required)"
     placeholder: "Paste the JSON text of your theme"
     render: json
   validations:
     required: true
 - type: input
   id: author
   attributes:
     label: "Author (optional)"
 - type: input
   id: author_url
   attributes:
     label: "Author URL (optional)"
 - type: input
   id: comment
   attributes:
     label: "Comment (optional)"
     placeholder: "Any additional information..."
